fix: lib/random32.c: Fix redefining a function by removing old redundant line
This commit 4913d2ffca70c79d38f0d8ad1ad212468490f136
caused this compiler to say

lib/random32.c:348:45: error: redefinition of 'net_rand_state' with a different type: 'typeof(struct siprand_state)' (aka 'struct siprand_state') vs 'typeof(struct rnd_state)' (aka 'struct rnd_state')
static DEFINE_PER_CPU(struct siprand_state, net_rand_state) __latent_entropy;
                                            ^
lib/random32.c:51:34: note: previous definition is here
DEFINE_PER_CPU(struct rnd_state, net_rand_state);
                                 ^
1 error generated.

Because there's another state of rnd_state call that came from samsung
division.

Now, this should fix the problem

ACK:
https://android-review.googlesource.com/c/kernel/common/+/1505211/2
67730020fa30616db76c367e3cbcf2828e51c0a7

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>