fix: drivers/usb/serial/pl2303.c: Undefined HP_LD381_PRODUCT_ID HWID error
From commit c02035933ac0ea6d6cb49c4afde34f973eefd523
The reason: flawed merge

drivers/usb/serial/pl2303.c:96:29: error: use of undeclared identifier 'HP_LD381_PRODUCT_ID'
        { USB_DEVICE(HP_VENDOR_ID, HP_LD381_PRODUCT_ID) },

in headers, the HP_LD381_PRODUCT_ID was undefined, or basically not
added

So i decided to add it in the headers, courtesy from the Linux 6.x repo

/* Hewlett-Packard POS Pole Displays */
#define HP_VENDOR_ID		0x03f0
#define HP_LD381GC_PRODUCT_ID	0x0183
#define HP_LM920_PRODUCT_ID	0x026b
#define HP_TD620_PRODUCT_ID	0x0956
#define HP_LD960_PRODUCT_ID	0x0b39
#define HP_LCM220_PRODUCT_ID	0x3139
#define HP_LCM960_PRODUCT_ID	0x3239
#define HP_LD220_PRODUCT_ID	0x3524
#define HP_LD220TA_PRODUCT_ID	0x4349
#define HP_LD960TA_PRODUCT_ID	0x4439
#define HP_LM940_PRODUCT_ID	0x5039
#define HP_LD381_PRODUCT_ID	0x0f7f <- The new ID

So the HP_LD381_PRODUCT_ID is now defined, and should no longer cause
any issues in the compiler.

ACK Commit:
https://android-review.googlesource.com/c/kernel/common/+/1464880
13abe236365485368755fb76c57a67a9b1f640d8

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>