fix: drivers/usb/class/cdc-acm : Satisfy missing functions
This commit e0c9fcd020fb420f786d827ed995ab3e18bf7429 caused
this error to happen

drivers/usb/class/cdc-acm.c:504:28: error: no member named 'urbs_in_error_delay' in 'struct acm'
                set_bit(rb->index, &acm->urbs_in_error_delay);
                                    ~~~  ^
drivers/usb/class/cdc-acm.c:505:11: error: use of undeclared identifier 'ACM_ERROR_DELAY'
                set_bit(ACM_ERROR_DELAY, &acm->flags);
                        ^
drivers/usb/class/cdc-acm.c:506:3: error: use of undeclared identifier 'cooldown'
                cooldown = true;
                ^
drivers/usb/class/cdc-acm.c:532:12: error: use of undeclared identifier 'cooldown'
                else if (cooldown)
                         ^
drivers/usb/class/cdc-acm.c:1632:7: error: no member named 'urbs_in_error_delay' in 'struct acm'
        acm->urbs_in_error_delay = 0;
        ~~~  ^
5 errors generated.

So we satisfy the required functions, and also imported some from the
4.19 stable branch

ACK:
https://android-review.googlesource.com/c/kernel/common/+/1488744/
d1253c75a8e09fe2976beb552f845e7af7688e8e

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>