fix: drivers/usb/dwc3/gadget.c: Fix expected expression from compiler towards gadget.c
This commit 4913d2ffca70c79d38f0d8ad1ad212468490f136
caused this compiler to say

drivers/usb/dwc3/gadget.c:2996:2: error: expected expression
        else if (dwc3_gadget_ep_should_continue(dep))
        ^
1 error generated.

due to missing brackets needed to form the if and elseif functions

This patch should fix it.

ACK:
https://android-review.googlesource.com/c/kernel/common/+/1505211/2
67730020fa30616db76c367e3cbcf2828e51c0a7

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>