fix: net/sched/sch_generic.c: Disabled flawed line related to qdisc_default which is an undefined identifier and removed an extra brace
This commit 4913d2ffca70c79d38f0d8ad1ad212468490f136
caused the compiler to show errors like this

net/sched/sch_generic.c:1150:40: error: use of undeclared identifier 'qdisc_default'
                rcu_assign_pointer(dev_queue->qdisc, qdisc_default);
                                                     ^
net/sched/sch_generic.c:1150:40: error: use of undeclared identifier 'qdisc_default'
net/sched/sch_generic.c:1157:1: error: extraneous closing brace ('}')
}
^
3 errors generated.

Due to flawed line of code:

static void dev_reset_queue(struct net_device *dev,
			    struct netdev_queue *dev_queue,
			    void *_unused)
{
	struct Qdisc *qdisc;
	bool nolock;

	qdisc = dev_queue->qdisc_sleeping;
	if (!qdisc)
		return;

	nolock = qdisc->flags & TCQ_F_NOLOCK;

		if (nolock)
			spin_lock_bh(&qdisc->seqlock);
		spin_lock_bh(qdisc_lock(qdisc));

		if (!(qdisc->flags & TCQ_F_BUILTIN))
			set_bit(__QDISC_STATE_DEACTIVATED, &qdisc->state);

		rcu_assign_pointer(dev_queue->qdisc, qdisc_default);
		qdisc_reset(qdisc);

		spin_unlock_bh(qdisc_lock(qdisc));
		if (nolock)
			spin_unlock_bh(&qdisc->seqlock);
	}
}

So, we fix it by doing this

static void dev_reset_queue(struct net_device *dev,
			    struct netdev_queue *dev_queue,
			    void *_unused)
{
	struct Qdisc *qdisc;
	bool nolock;

	qdisc = dev_queue->qdisc_sleeping;
	if (!qdisc)
		return;

	nolock = qdisc->flags & TCQ_F_NOLOCK;

	if (nolock)
		spin_lock_bh(&qdisc->seqlock);
	spin_lock_bh(qdisc_lock(qdisc));

	// if (!(qdisc->flags & TCQ_F_BUILTIN))
	// 	set_bit(__QDISC_STATE_DEACTIVATED, &qdisc->state);

	// rcu_assign_pointer(dev_queue->qdisc, qdisc_default);
	qdisc_reset(qdisc);

	spin_unlock_bh(qdisc_lock(qdisc));
	if (nolock)
		spin_unlock_bh(&qdisc->seqlock);

}

It should /theoretically/ solve the error.

ACK:
https://android-review.googlesource.com/c/kernel/common/+/1505211/2
67730020fa30616db76c367e3cbcf2828e51c0a7

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>