fix: security/keys/keyctl.c: Fix compile error, use of undeclared identifier 'key_data' and 'key_data_len', by commenting it.
From Commit 5747519267a8ffdf1fadf6e17d6686d47f1d1b64
is causing the issue.

security/keys/keyctl.c:800:12: error: use of undeclared identifier 'key_data'
        __kvzfree(key_data, key_data_len);
                  ^
security/keys/keyctl.c:800:22: error: use of undeclared identifier 'key_data_len'
        __kvzfree(key_data, key_data_len);
                            ^

So the solution was to comment out the
__kvzfree(key_data, key_data_len);
since it seems we are actually not using this component.

I guess samsung doesn't use this? I studied other commits and it seems
this was the only instance of the keyctl.c being modified.

ACK Commit:
https://android-review.googlesource.com/c/kernel/common/+/1344665
4d01d462e6b68c459fc4b77cdde3fa5671aef6a6

See: security/keys/keyctl.c
Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>