fix: drivers/usb/class/cdc-acm.c: Removing flawed INIT_WORK call
This commit e9d2cca9a29308942c89d63efa1514c89943ba9b
caused catastrophic error during compiling, primarily in using the
'work' member, instead of 'dwork' member

drivers/usb/class/cdc-acm.c:1400:18: error: no member named 'work' in 'struct acm'; did you mean 'dwork'?
        INIT_WORK(&acm->work, acm_softint);
                        ^~~~
                        dwork
./include/linux/workqueue.h:256:15: note: expanded from macro 'INIT_WORK'
        __INIT_WORK((_work), (_func), 0)
                     ^
./include/linux/workqueue.h:248:16: note: expanded from macro '__INIT_WORK'
                __init_work((_work), _onstack);                         \
                             ^
drivers/usb/class/cdc-acm.h:114:22: note: 'dwork' declared here
        struct delayed_work dwork;                      /* work queue entry for various purposes */
                            ^
drivers/usb/class/cdc-acm.c:1400:18: error: no member named 'work' in 'struct acm'; did you mean 'dwork'?
        INIT_WORK(&acm->work, acm_softint);
                        ^~~~
                        dwork
./include/linux/workqueue.h:256:15: note: expanded from macro 'INIT_WORK'
        __INIT_WORK((_work), (_func), 0)
                     ^
./include/linux/workqueue.h:249:4: note: expanded from macro '__INIT_WORK'
                (_work)->data = (atomic_long_t) WORK_DATA_INIT();       \
                 ^
drivers/usb/class/cdc-acm.h:114:22: note: 'dwork' declared here
        struct delayed_work dwork;                      /* work queue entry for various purposes */
                            ^
drivers/usb/class/cdc-acm.c:1400:2: error: no member named 'data' in 'struct delayed_work'
        INIT_WORK(&acm->work, acm_softint);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/workqueue.h:256:2: note: expanded from macro 'INIT_WORK'
        __INIT_WORK((_work), (_func), 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/workqueue.h:249:12: note: expanded from macro '__INIT_WORK'
                (_work)->data = (atomic_long_t) WORK_DATA_INIT();       \
                ~~~~~~~  ^
drivers/usb/class/cdc-acm.c:1400:18: error: no member named 'work' in 'struct acm'; did you mean 'dwork'?
        INIT_WORK(&acm->work, acm_softint);
                        ^~~~
                        dwork
./include/linux/workqueue.h:256:15: note: expanded from macro 'INIT_WORK'
        __INIT_WORK((_work), (_func), 0)
                     ^
./include/linux/workqueue.h:250:20: note: expanded from macro '__INIT_WORK'
                INIT_LIST_HEAD(&(_work)->entry);                        \
                                 ^
drivers/usb/class/cdc-acm.h:114:22: note: 'dwork' declared here
        struct delayed_work dwork;                      /* work queue entry for various purposes */
                            ^
drivers/usb/class/cdc-acm.c:1400:2: error: no member named 'entry' in 'struct delayed_work'
        INIT_WORK(&acm->work, acm_softint);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/workqueue.h:256:2: note: expanded from macro 'INIT_WORK'
        __INIT_WORK((_work), (_func), 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/workqueue.h:250:28: note: expanded from macro '__INIT_WORK'
                INIT_LIST_HEAD(&(_work)->entry);                        \
                                ~~~~~~~  ^
drivers/usb/class/cdc-acm.c:1400:18: error: no member named 'work' in 'struct acm'; did you mean 'dwork'?
        INIT_WORK(&acm->work, acm_softint);
                        ^~~~
                        dwork
./include/linux/workqueue.h:256:15: note: expanded from macro 'INIT_WORK'
        __INIT_WORK((_work), (_func), 0)
                     ^
./include/linux/workqueue.h:251:4: note: expanded from macro '__INIT_WORK'
                (_work)->func = (_func);                                \
                 ^
drivers/usb/class/cdc-acm.h:114:22: note: 'dwork' declared here
        struct delayed_work dwork;                      /* work queue entry for various purposes */
                            ^
drivers/usb/class/cdc-acm.c:1400:2: error: no member named 'func' in 'struct delayed_work'
        INIT_WORK(&acm->work, acm_softint);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/workqueue.h:256:2: note: expanded from macro 'INIT_WORK'
        __INIT_WORK((_work), (_func), 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/workqueue.h:251:12: note: expanded from macro '__INIT_WORK'
                (_work)->func = (_func);                                \
                ~~~~~~~  ^
7 errors generated.

Though, this INIT_WORK function call is already been removed from
4.19-stable (4.19.155) so i was actually looking at a wrong reference
on the previous patch.

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>