fix: include/linux/virtio_net.h: Reverting .131 Commit, due to differences in funcalls
From Commit ba90b1c59ff3ebd6f3b0c4e533eace14978f9f7f
is causing this issue

In file included from net/packet/af_packet.c:88:
./include/linux/virtio_net.h:88:4: error: use of undeclared identifier 'shinfo'
  CC      drivers/base/topology.o
                        shinfo->gso_type |= SKB_GSO_DODGY;
                        ^
./include/linux/virtio_net.h:89:4: error: use of undeclared identifier 'shinfo'
                        shinfo->gso_segs = 0;
                        ^
./include/linux/virtio_net.h:93:2: error: expected identifier or '('
        return 0;
        ^
./include/linux/virtio_net.h:94:1: error: extraneous closing brace ('}')
}
^

And the core of it:

	} < also causes that extraneous closing brace error

	if (hdr->gso_type != VIRTIO_NET_HDR_GSO_NONE) {
		u16 gso_size = __virtio16_to_cpu(little_endian, hdr->gso_size);

		skb_shinfo(skb)->gso_size = gso_size;
		skb_shinfo(skb)->gso_type = gso_type;

			/* Header must be checked, and gso_segs computed. */
			shinfo->gso_type |= SKB_GSO_DODGY;
			shinfo->gso_segs = 0;
		}
	}

	return 0;
}

and fixed to this

	if (hdr->gso_type != VIRTIO_NET_HDR_GSO_NONE) {
			u16 gso_size = __virtio16_to_cpu(little_endian, hdr->gso_size);

			skb_shinfo(skb)->gso_size = gso_size;
			skb_shinfo(skb)->gso_type = gso_type;

			/* Header must be checked, and gso_segs computed. */
			skb_shinfo(skb)->gso_type |= SKB_GSO_DODGY;
			skb_shinfo(skb)->gso_segs = 0;
		}
	}

	return 0;
}

Because samsung has different approaches, it seems.

Blame commit from Google ACK: b3293788b984743b5cf768587efe6c2c2d6f4f52
Link: https://android-review.googlesource.com/c/kernel/common/+/1353891

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>