fix: net/netlink/genetlink.c: Fix issue of member missing called mcast_bind and mcast_unbind when being indexed at compile
This merge commit 9a443c9a7a25de5554ac4d18c54d14b28e14ebdf
Caused net/netlink/genetlink.c to have this error

net/netlink/genetlink.c:979:16: error: no member named 'mcast_bind' in 'struct genl_family'
                        else if (f->mcast_bind)
                                 ~  ^
net/netlink/genetlink.c:980:14: error: no member named 'mcast_bind' in 'struct genl_family'
                                err = f->mcast_bind(net, fam_grp);
                                      ~  ^
net/netlink/genetlink.c:1003:11: error: no member named 'mcast_unbind' in 'struct genl_family'
                        if (f->mcast_unbind)
                            ~  ^
net/netlink/genetlink.c:1004:8: error: no member named 'mcast_unbind' in 'struct genl_family'
                                f->mcast_unbind(net, fam_grp);
                                ~  ^
4 errors generated.

So far, that is the only issue and as i checked the
other commits, it seems that commit 9a443c9a7a25de5554ac4d18c54d14b28e14ebdf
is the one causing the issue.

My assumption would be the deletion of this:

		.bind		= genl_bind,
		.unbind		= genl_unbind,

from

static int __net_init genl_pernet_init(struct net *net)
{
	struct netlink_kernel_cfg cfg = {
		.input		= genl_rcv,
		.flags		= NL_CFG_F_NONROOT_RECV,
	};

	/* we'll bump the group number right afterwards */
	net->genl_sock = netlink_kernel_create(net, NETLINK_GENERIC, &cfg);

	if (!net->genl_sock && net_eq(net, &init_net))
		panic("GENL: Cannot initialize generic netlink\n");

	if (!net->genl_sock)
		return -ENOMEM;

	return 0;
}

in start line 1011.

which we need it to be like this:

static int __net_init genl_pernet_init(struct net *net)
{
	struct netlink_kernel_cfg cfg = {
		.input		= genl_rcv,
		.flags		= NL_CFG_F_NONROOT_RECV,
		.bind		= genl_bind,
		.unbind		= genl_unbind,
	};

	/* we'll bump the group number right afterwards */
	net->genl_sock = netlink_kernel_create(net, NETLINK_GENERIC, &cfg);

	if (!net->genl_sock && net_eq(net, &init_net))
		panic("GENL: Cannot initialize generic netlink\n");

	if (!net->genl_sock)
		return -ENOMEM;

	return 0;
}

then again, im just guessing here. It would be nice if this fixes the issue.

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>