fix: drivers/usb/dwc3/gadget.c: Fix duplicate invocation of 'true' towards dwc3_stop_active_transfer(struct dwc3_ep *dep, bool force);
This commit 50b053b96e1c8dbbebfe351ae765043e8391c142
drivers/usb/dwc3/gadget.c line 1428, col 40, caused this error
in the Compile Runtime:

drivers/usb/dwc3/gadget.c:1428:40: error: too many arguments to function call, expected 2, have 3
                dwc3_stop_active_transfer(dep, true, true);
                ~~~~~~~~~~~~~~~~~~~~~~~~~            ^~~~
drivers/usb/dwc3/gadget.c:787:1: note: 'dwc3_stop_active_transfer' declared here
static void dwc3_stop_active_transfer(struct dwc3_ep *dep, bool force);
^
1 error generated.
make[3]: *** [scripts/Makefile.build:333: drivers/usb/dwc3/gadget.o] Error 1
make[3]: *** Waiting for unfinished jobs....

The root commit is actually came from Google's ACK:
https://android-review.googlesource.com/c/kernel/common/+/1351922
With Merge ID: b96549a28b845cac5d48e793dbdb1b9fd8f23aa8

Idk why VS code did not flare a warning and just approved the changes
immediately while making the function to have triargs than dualargs

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>