fix:kernel/reboot.c: Fix error of undeclared error in reboot.c
This commit 4913d2ffca70c79d38f0d8ad1ad212468490f136
caused the compiler to say

kernel/reboot.c:578:6: error: use of undeclared identifier 'mode'
                                *mode = REBOOT_SOFT;
                                 ^
1 error generated.

So we decided to add this

enum reboot_mode *mode;

to the code since it seems ACK set this as standard

And thus we have this:

static int __init reboot_setup(char *str)
{
	for (;;) {
		/*
		 * Having anything passed on the command line via
		 * reboot= will cause us to disable DMI checking
		 * below.
		 */
		reboot_default = 0;
		/*
		 * Even though we already have the Samsung standard to *mode as reboot_mode directly
		 * we should add this by adding this specific line of code.
		 * enum reboot_mode *mode;
		 * to avoid another fail again, since it seems ACK only prefer *mode as reboot_mode.
		 */
		enum reboot_mode *mode;

		switch (*str) {
		case 'w':
			reboot_mode = REBOOT_WARM;
			break;

		case 'c':
			reboot_mode = REBOOT_COLD;
			break;

		case 'h':
			reboot_mode = REBOOT_HARD;
			break;

		case 's':
			if (isdigit(*(str+1)))
				reboot_cpu = simple_strtoul(str+1, NULL, 0);
			else if (str[1] == 'm' && str[2] == 'p' &&
							isdigit(*(str+3)))
				reboot_cpu = simple_strtoul(str+3, NULL, 0);
			else
				*mode = REBOOT_SOFT;
			if (reboot_cpu >= num_possible_cpus()) {
				pr_err("Ignoring the CPU number in reboot= option. "
				       "CPU %d exceeds possible cpu number %d\n",
				       reboot_cpu, num_possible_cpus());
				reboot_cpu = 0;
				break;
			}
			break;

		case 'g':
			reboot_mode = REBOOT_GPIO;
			break;

		case 'b':
		case 'a':
		case 'k':
		case 't':
		case 'e':
		case 'p':
			reboot_type = *str;
			break;

		case 'f':
			reboot_force = 1;
			break;
		}

		str = strchr(str, ',');
		if (str)
			str++;
		else
			break;
	}
	return 1;
}

ACK:
https://android-review.googlesource.com/c/kernel/common/+/1505211/2
67730020fa30616db76c367e3cbcf2828e51c0a7

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>