fix: drivers/spi/spi-s3c64xx.c: Revert changes from 154, because a lot of things were borked
From Commit d77c108fe0b55abb8c68e6d479c48479be4a006a

The commit caused these errors

drivers/spi/spi-s3c64xx.c:142:8: error: redefinition of 's3c64xx_spi_dma_data'
struct s3c64xx_spi_dma_data {
       ^
./include/linux/platform_data/spi-s3c64xx.h:89:8: note: previous definition is here
struct s3c64xx_spi_dma_data {
       ^
drivers/spi/spi-s3c64xx.c:256:20: error: use of undeclared identifier 'SPI_DBG_MODE'
                        sci->dbg_mode = SPI_DBG_MODE | SPI_LOOPBACK_MODE;
                                        ^
drivers/spi/spi-s3c64xx.c:256:35: error: use of undeclared identifier 'SPI_LOOPBACK_MODE'
                        sci->dbg_mode = SPI_DBG_MODE | SPI_LOOPBACK_MODE;
                                                       ^
drivers/spi/spi-s3c64xx.c:261:20: error: use of undeclared identifier 'SPI_DBG_MODE'
                        sci->dbg_mode = SPI_DBG_MODE;
                                        ^
drivers/spi/spi-s3c64xx.c:393:10: error: no member named 'fifo' in 'struct dma_slave_config'
                config.fifo = sdd->sfr_start + S3C64XX_SPI_RX_DATA;
                ~~~~~~ ^
drivers/spi/spi-s3c64xx.c:394:10: error: no member named 'width' in 'struct dma_slave_config'
                config.width = sdd->cur_bpw / 8;
                ~~~~~~ ^
drivers/spi/spi-s3c64xx.c:395:3: error: use of undeclared identifier 'modecfg'
                modecfg = readl(sdd->regs + S3C64XX_SPI_MODE_CFG);
                ^
drivers/spi/spi-s3c64xx.c:396:10: error: no member named 'maxburst' in 'struct dma_slave_config'
                config.maxburst = modecfg & S3C64XX_SPI_MODE_4BURST ?
                ~~~~~~ ^
drivers/spi/spi-s3c64xx.c:396:21: error: use of undeclared identifier 'modecfg'
                config.maxburst = modecfg & S3C64XX_SPI_MODE_4BURST ?
                                  ^
drivers/spi/spi-s3c64xx.c:426:7: error: no member named 'cookie' in 'struct s3c64xx_spi_dma_data'
        dma->cookie = dmaengine_submit(desc);
        ~~~  ^
drivers/spi/spi-s3c64xx.c:427:30: error: no member named 'cookie' in 'struct s3c64xx_spi_dma_data'
        ret = dma_submit_error(dma->cookie);
                               ~~~  ^
drivers/spi/spi-s3c64xx.c:442:24: error: no member named 'no_cs' in 'struct s3c64xx_spi_info'
        if (sdd->cntrlr_info->no_cs)
            ~~~~~~~~~~~~~~~~  ^
drivers/spi/spi-s3c64xx.c:446:25: error: no member named 'quirks' in 'struct s3c64xx_spi_port_config'
                if (!(sdd->port_conf->quirks & S3C64XX_SPI_QUIRK_CS_AUTO)) {
                      ~~~~~~~~~~~~~~  ^
drivers/spi/spi-s3c64xx.c:446:34: error: use of undeclared identifier 'S3C64XX_SPI_QUIRK_CS_AUTO'
                if (!(sdd->port_conf->quirks & S3C64XX_SPI_QUIRK_CS_AUTO)) {
                                               ^
drivers/spi/spi-s3c64xx.c:456:25: error: no member named 'quirks' in 'struct s3c64xx_spi_port_config'
                if (!(sdd->port_conf->quirks & S3C64XX_SPI_QUIRK_CS_AUTO))
                      ~~~~~~~~~~~~~~  ^
drivers/spi/spi-s3c64xx.c:456:34: error: use of undeclared identifier 'S3C64XX_SPI_QUIRK_CS_AUTO'
                if (!(sdd->port_conf->quirks & S3C64XX_SPI_QUIRK_CS_AUTO))
                                               ^
drivers/spi/spi-s3c64xx.c:571:3: error: use of undeclared identifier 'dma_burst_len'
                dma_burst_len = (sdd->cur_bpw / 8) * S3C64XX_SPI_DMA_4BURST_LEN;
                ^
drivers/spi/spi-s3c64xx.c:572:21: error: use of undeclared identifier 'dma_burst_len'
                if (!(xfer->len % dma_burst_len))
                                  ^
drivers/spi/spi-s3c64xx.c:581:3: error: use of undeclared identifier 'packet_cnt_en'
                packet_cnt_en = readl(regs + S3C64XX_SPI_PACKET_CNT);
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [scripts/Makefile.build:334: drivers/spi/spi-s3c64xx.o] Error 1
make[2]: *** Waiting for unfinished jobs....

I guess that what happens if you unilaterally
approve a change lmao.

But still i will retry patching this up

ACK Commit:
https://android-review.googlesource.com/c/kernel/common/+/1478997
b9a942466bc38a32a2e4be23234dec645605559e

Signed-off-by: Mizumo-prjkt <bluepearl394@gmail.com>